//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BUSTICKETINGEntities : DbContext
    {
        public BUSTICKETINGEntities()
            : base("name=BUSTICKETINGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BUS_ASSIGN> BUS_ASSIGN { get; set; }
        public DbSet<DUSER> DUSERs { get; set; }
        public DbSet<MODULE_PERMISSION> MODULE_PERMISSION { get; set; }
        public DbSet<PRE_SETUP> PRE_SETUP { get; set; }
        public DbSet<ROLEWISE_MENU> ROLEWISE_MENU { get; set; }
        public DbSet<SeatFareDetail> SeatFareDetails { get; set; }
        public DbSet<TICKET_DETAILS> TICKET_DETAILS { get; set; }
        public DbSet<USER_GROUP> USER_GROUP { get; set; }
    }
}
