//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUSER
    {
        public DUSER()
        {
            this.TICKET_DETAILS = new HashSet<TICKET_DETAILS>();
        }
    
        public int USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public long USER_GROUP_ID { get; set; }
    
        public virtual USER_GROUP USER_GROUP { get; set; }
        public virtual ICollection<TICKET_DETAILS> TICKET_DETAILS { get; set; }
    }
}
