//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULE_PERMISSION
    {
        public MODULE_PERMISSION()
        {
            this.ROLEWISE_MENU = new HashSet<ROLEWISE_MENU>();
        }
    
        public int ID { get; set; }
        public string MODULE_NAME { get; set; }
        public Nullable<long> USER_GROUP_ID { get; set; }
    
        public virtual USER_GROUP USER_GROUP { get; set; }
        public virtual ICollection<ROLEWISE_MENU> ROLEWISE_MENU { get; set; }
    }
}
