//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_SETUP
    {
        public int ID { get; set; }
        public string Time { get; set; }
        public string BusType { get; set; }
        public string Sift { get; set; }
        public string BusNumber { get; set; }
        public string TicketCounterName { get; set; }
    }
}
