//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_DETAILS
    {
        public int Id { get; set; }
        public string Time { get; set; }
        public Nullable<int> BusAssingnPKId { get; set; }
        public string BusUniqueCode { get; set; }
        public Nullable<int> ClintId { get; set; }
        public string ClintName { get; set; }
        public string Gender { get; set; }
        public string ClintAddress { get; set; }
        public string ClintMobile { get; set; }
        public string BusNo { get; set; }
        public string BusType { get; set; }
        public string Sift { get; set; }
        public string Status { get; set; }
        public string SeatNo { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> TicketPrice { get; set; }
        public Nullable<int> TicketPricePaid { get; set; }
        public Nullable<int> TicketPriceDiscount { get; set; }
        public Nullable<int> TicketPriceDue { get; set; }
        public string TicketNo { get; set; }
        public string BookingNo { get; set; }
        public Nullable<System.DateTime> JournyDate { get; set; }
        public string JournyFrom { get; set; }
        public string JournyTo { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual BUS_ASSIGN BUS_ASSIGN { get; set; }
        public virtual DUSER DUSER { get; set; }
    }
}
