//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_GROUP
    {
        public USER_GROUP()
        {
            this.DUSERs = new HashSet<DUSER>();
            this.MODULE_PERMISSION = new HashSet<MODULE_PERMISSION>();
            this.ROLEWISE_MENU = new HashSet<ROLEWISE_MENU>();
        }
    
        public long GROUP_ID { get; set; }
        public string GROUP_NAME { get; set; }
    
        public virtual ICollection<DUSER> DUSERs { get; set; }
        public virtual ICollection<MODULE_PERMISSION> MODULE_PERMISSION { get; set; }
        public virtual ICollection<ROLEWISE_MENU> ROLEWISE_MENU { get; set; }
    }
}
