//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using ENTITY.Login;
        ///using DATA;
        ///
        ///namespace DAL.LoginDAL
        ///{
        ///   public class MenuPermissionGateway
        ///    {
        ///       private POSMSEntities _hasanSecurityDataContextObj;
        ///        public bool SaveMenuUserGroupWise(EMenuPermission objMenu)
        ///        {
        ///            _hasanSecurityDataContextObj = new POSMSEntities();
        ///            var newMenu = new ROLEWISE_MENU
        ///            {
        ///                MO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MenuPermissionGateway {
            get {
                return ResourceManager.GetString("MenuPermissionGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using ENTITY.Login;
        ///using DATA;
        ///
        ///namespace DAL.LoginDAL
        ///{
        ///   public class SModulePermissionGateway
        ///    {
        ///       private POSMSEntities _hasanSecurityDataContextObj;
        ///        public bool SaveModulePermission(ESModulePermission objEsModPer)
        ///        {
        ///            _hasanSecurityDataContextObj = new POSMSEntities();
        ///            var Module = new MODULE_PERMISSION
        ///            {
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SModulePermissionGateway {
            get {
                return ResourceManager.GetString("SModulePermissionGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using ENTITY.Login;
        ///using DATA;
        ///
        ///namespace DAL.LoginDAL
        ///{
        ///   public class SUserGateway
        ///    {
        ///       private POSMSEntities _hasanSecurityDataContextObj;
        ///        public bool SaveUserInfo(ESUser anUser)
        ///        {
        ///            _hasanSecurityDataContextObj = new POSMSEntities();
        ///            var newUser = new DUSER
        ///            {
        ///                USER_NAME = anUser.UserName,
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SUserGateway {
            get {
                return ResourceManager.GetString("SUserGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using ENTITY.Login;
        ///using DATA;
        ///
        ///namespace DAL.LoginDAL
        ///{
        ///   public class SUserGroupGateway
        ///    {
        ///       private POSMSEntities _hasanSecurityDataContextObj;
        ///        public bool SaveUserGroup(ESUserGroup anEuserGroup)
        ///        {
        ///            _hasanSecurityDataContextObj = new POSMSEntities();
        ///
        ///            var newUserGroup = new USER_GROUP
        ///            {
        ///                GROUP_NAM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SUserGroupGateway {
            get {
                return ResourceManager.GetString("SUserGroupGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using ENTITY.Login;
        ///using DATA;
        ///
        ///namespace DAL.LoginDAL
        ///{
        ///   public class UserGateway
        ///    {
        ///       private POSMSEntities hasanMainDataContectObj;
        ///        public MMEUser GetAllInfoforSingleUser(MMEUser anUser)
        ///        {
        ///            hasanMainDataContectObj = new POSMSEntities();
        ///            var query = from j in hasanMainDataContectObj.DUSERs
        ///                        where j.USER [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserGateway {
            get {
                return ResourceManager.GetString("UserGateway", resourceCulture);
            }
        }
    }
}
